name: Godot build
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: combine-carnage
  
jobs:
  export:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        export:
          - name: windows
            preset: Windows Desktop
            filename: $EXPORT_NAME.exe
          - name: linux
            preset: Linux/X11
            filename: $EXPORT_NAME.x86_64
          - name: macos
            preset: Mac OSX
            filename: $EXPORT_NAME.zip
          - name: html5
            preset: "HTML5"
            filename: index.html
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Godot Export
        run: |
          mkdir -v -p ./build/${{matrix.export.name}}
          godot -v --export "${{matrix.export.preset}}" ./build/${{matrix.export.name}}/${{matrix.export.filename}}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.export.name}}
          path: ./build/${{matrix.export.name}}
  deploy:
    needs:
      - export
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/deploy-pages@v1.2.3
        with:
          token: ${{ github.token }}
          artifact_name: html5